@baseUrl = http://127.0.0.1:8051/api
# @baseUrl = https://mcp.so/api

###
POST {{baseUrl}}/submit-project
Content-Type: application/json

{
  "url": "https://github.com/minecraft-linux/mcpelauncher-server",
  "content": "",
  "status": "deleted",
  "is_featured": false,
  "sort": 0
}

###
POST {{baseUrl}}/submit-projects
Content-Type: application/json

[
  {
    "url": "https://github.com/ch/mcp-server-chatsum1"
  },
  {
    "url": "https://github.com/ch/mcp-server-chatsum2"
  }
]

###
POST {{baseUrl}}/summarize-project
Content-Type: application/json

{
  "name": "git"
}

###
POST {{baseUrl}}/summarize-projects
Content-Type: application/json

{
  "page": 1,
  "limit": 200
}

###
POST {{baseUrl}}/update-sitemaps
Content-Type: application/json

{
  "batch_no": 1,
  "limit": 500,
  "page_step": 5
}
