# @baseUrl = http://127.0.0.1:8051/api
@baseUrl = https://mcp.so/api

###
POST {{baseUrl}}/submit-project
Content-Type: application/json

{
  "url": "https://github.com/KashiwaByte/vikingdb-mcp-server"
}
